name: build and deploy to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@v0.12.0
      env:
        TOKEN: ${{ secrets.TOKEN }}
