name: build and deploy to GitHub Pages

# see https://github.com/shalzz/zola-deploy-action/blob/9d5b8372d847dc57b688a29b87726d897b468cde/README.md

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: 'checkout'
        uses: actions/checkout@master
      - name: 'build only'
        uses: shalzz/zola-deploy-action@master
        env:
          TOKEN: ${{ secrets.TOKEN }}
          BUILD_ONLY: true
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 'checkout'
        uses: actions/checkout@master
      - name: 'build and deploy'
        uses: shalzz/zola-deploy-action@master
        env:
          TOKEN: ${{ secrets.TOKEN }}
